export type LayoutSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'

export type LayoutAlignment = 'left' | 'right' | 'center'

export type Color =
  | 'red'
  | 'pink'
  | 'purple'
  | 'deep-purple'
  | 'indigo'
  | 'blue'
  | 'light-blue'
  | 'cyan'
  | 'teal'
  | 'green'
  | 'light-green'
  | 'lime'
  | 'yellow'
  | 'amber'
  | 'orange'
  | 'deep-orange'
  | 'brown'
  | 'blue-grey'
  | 'grey'
